### ISSUE TITLE
Change time limit of recording

### ISSUE THREAD

**Issue by durimrexhaj** [imalhasaranga/VideoRecorderJs#2]
Hi there.

I'm using html5_video_audio_recorder and i wanted to know how can i change the time limit of capturing the audio because after 30 seconds the video is not captured just the audio.

Thanks.

**Comment by ordavidil** [comment]
Hey,  
I also had this problem,

go to _whammy.js_  line 152 and change it to:

```
"data": Math.round(clusterTimecode),
```

**Comment by imalhasaranga** [comment]
@ordavidil  please fix the bug if you can,  I'm not getting much time recently

**Comment by imalhasaranga** [comment]
This issue has been resolved with the latest relese
