### ISSUE TITLE
Quality of sound

### ISSUE THREAD

**Issue by anaay** [imalhasaranga/VideoRecorderJs#3]
Good evening,

I'm trying to use your app (with Chrome) and I'm facing a problem. The sound recorded is not clear, it's like there is echo but the gain is set at 0. I'm not sure whether it comes from my computer/microphone or from the settings. Did anyone else also have this problem ?

Moreover, did anyone find out how to handle the time limit recording issue ?

Thanks.

**Comment by imalhasaranga** [comment]
Your issue has been taken to the account while releasing the 1.0.0
