### ISSUE TITLE
Uncaught TypeError: Cannot read property 'size' of undefined

### ISSUE THREAD

**Issue by Suganya-Rajasekar** [imalhasaranga/VideoRecorderJs#7]
I'm getting this error while uploading.

[http://i.prntscr.com/5776489b4c5843ffac653f2a560e48ef.png](http://i.prntscr.com/5776489b4c5843ffac653f2a560e48ef.png)

how should I resolve this

**Comment by yeisson** [comment]
I have the same problem.
Any suggestions?

**Comment by imalhasaranga** [comment]
I'm really sorry for these late replies, but this bug has been fixed in the upcoming version 2.0.0,
also I'm going to deprecate 

```
uploadData() 
``` 

function because I feel it should not be a part of this library.. do you guys have any thoughts on this ?
